import React, { useState } from "react";
import { Link, useLocation } from "react-router-dom";

// Images
import solar from "../assets/Solar_Energy.jpg";
import wind from "../assets/Wind_Energy.jpg";
import hydro from "../assets/Hydro_Energy.jpg";
import biomass from "../assets/Biomass_Energy.jpg";
import geothermal from "../assets/geothermal.jpg";
import ocean from "../assets/Ocean_Energy.jpg";

const Renewable = () => {
  const location = useLocation();
  const highlightedId = location.state?.selectedId || null;

  const [searchTerm, setSearchTerm] = useState("");

  const renewableProjects = [
    {
      id: 1,
      name: "Solar Energy",
      img: solar,
      desc: "Solar energy uses sunlight to produce electricity using photovoltaic systems.",
      advantages: ["Eco-friendly, renewable and clean", "Low maintenance", "Reduces electricity bills"],
      disadvantages: ["Depends on sunlight availability", "High initial installation cost", "Requires large area for big systems"],
      examples: ["Rooftop solar panels", "Solar water heaters", "Large solar farms (Bhadla Solar Park, India)"],
      rating: 5,
      efficiency: 75,
      impact: 20
    },
    {
      id: 2,
      name: "Wind Energy",
      img: wind,
      desc: "Wind turbines convert wind kinetic energy into electricity.",
      advantages: ["Highly renewable and abundant", "Cost-effective in windy regions", "Zero emissions during operation"],
      disadvantages: ["Noisy turbines", "Requires open land", "Wind is inconsistent"],
      examples: ["Offshore wind farms", "Onshore turbines in Tamil Nadu", "UK Hornsea Wind Farm"],
      rating: 4,
      efficiency: 60,
      impact: 30
    },
    {
      id: 3,
      name: "Hydro Energy",
      img: hydro,
      desc: "Electricity generated by the movement of water in dams and rivers.",
      advantages: ["Highly efficient (90%+)", "Reliable and constant source", "Supports irrigation & flood control"],
      disadvantages: ["Expensive dam construction", "Affects aquatic life", "Can displace local communities"],
      examples: ["Tehri Dam (India)", "Three Gorges Dam (China)"],
      rating: 4,
      efficiency: 90,
      impact: 40
    },
    {
      id: 4,
      name: "Biomass Energy",
      img: biomass,
      desc: "Organic waste used to generate heat or electricity.",
      advantages: ["Reduces waste", "Easily available raw materials", "Carbon-neutral"],
      disadvantages: ["Emits some pollution", "Can require large storage", "Lower efficiency than fossil fuels"],
      examples: ["Biogas plants", "Agricultural waste burning plants"],
      rating: 3,
      efficiency: 50,
      impact: 50
    },
    {
      id: 5,
      name: "Geothermal Energy",
      img: geothermal,
      desc: "Energy from heat inside the Earth used for electricity and heating.",
      advantages: ["Very reliable 24/7", "Low emissions", "Small land footprint"],
      disadvantages: ["Location-specific (geothermal zones only)", "High drilling cost", "May release underground gases"],
      examples: ["Iceland geothermal stations", "California Geysers"],
      rating: 4,
      efficiency: 80,
      impact: 25
    },
    {
      id: 6,
      name: "Ocean Energy",
      img: ocean,
      desc: "Ocean energy is generated from tides, waves, and thermal gradients, providing a predictable renewable power source.",
      advantages: ["Highly predictable energy source", "Huge potential due to oceans", "Eco-friendly", "Suitable for coastal regions", "Low visual impact"],
      disadvantages: ["High installation and maintenance cost", "Corrosion due to salt water", "Affects marine ecosystems", "Requires advanced technology", "Limited to coastal regions"],
      examples: ["Tidal power stations (Sihwa Lake, South Korea)", "Wave energy converters", "OTEC plants", "Floating wave buoys", "Underwater tidal turbines"],
      rating: 4,
      efficiency: 72,
      impact: 40
    }
  ];

  // Filter projects by search term
  const filteredProjects = renewableProjects.filter(
    (energy) =>
      energy.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      energy.desc.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <>
     {/* ================= HERO SECTION (Plain & Attractive) ================= */}
<section
  className="text-white text-center d-flex align-items-center justify-content-center"
  style={{
    height: "45vh",
    background:
    "linear-gradient(rgba(0,150,0,0.6), rgba(0,150,0,0.6)), url('https://images.unsplash.com/photo-1581092333821-3f86b0f45ab2?auto=format&fit=crop&w=1400&q=80')",
    // borderBottomLeftRadius: "60px",
    // borderBottomRightRadius: "60px",
    boxShadow: "0 10px 25px rgba(0,0,0,0.2)",
  }}
>
  <div className="p-4">
    <h1 className="fw-bold display-5 animate__animated animate__fadeInDown">
      🌱 Renewable Energy Sources
    </h1>

    <p className="mt-3 fs-5 text-light opacity-75 animate__animated animate__fadeInUp">
      Clean • Sustainable • Future-Focused Energy Solutions
    </p>

    {/* Soft Glow Decorative Line */}
    <div
      style={{
        width: "160px",
        height: "4px",
        background: "white",
        margin: "15px auto",
        borderRadius: "20px",
        boxShadow: "0 0 12px white",
      }}
    ></div>
  </div>
</section>




      {/* Search Filter */}
      {/* <div className="container text-center my-4">
        <input
          type="text"
          className="form-control w-50 mx-auto"
          placeholder="Search energy types..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div> */}

      {/* Highlighted Card */}
      {highlightedId && (
        <div className="text-center mt-3">
          <h5 className="fw-bold text-success">
            Highlighted → {renewableProjects.find(p => p.id === highlightedId)?.name}
          </h5>
        </div>
      )}

      {/* Cards */}
      <div className="container my-5">
        <div className="row g-4">
          {filteredProjects.map((energy) => (
            <div key={energy.id} className="col-md-4">
              <div
                className={`card h-100 shadow border-0 rounded-4 ${
                  energy.id === highlightedId ? "border border-3 border-success shadow-lg" : ""
                }`}
                style={{
                  overflow: "hidden",
                  transition: "all 0.3s",
                  cursor: "pointer",
                  transform: energy.id === highlightedId ? "scale(1.05)" : "scale(1)",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.transform = "translateY(-10px)";
                  e.currentTarget.style.boxShadow = "0 10px 30px rgba(0,0,0,0.2)";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.transform = "translateY(0)";
                  e.currentTarget.style.boxShadow = "0 5px 15px rgba(0,0,0,0.1)";
                }}
              >
                <img
                  src={energy.img}
                  alt={energy.name}
                  className="card-img-top"
                  style={{ height: "220px", objectFit: "cover" }}
                />
                <div className="card-body text-center">
                  <h4 className="fw-bold text-success">{energy.name}</h4>
                  <p className="text-secondary">{energy.desc}</p>
                  <Link
                    to="/details"
                    state={{ energy, backPage: "/renewable" }}
                    className="btn btn-success mt-2 px-4 rounded-pill"
                  >
                    View Details →
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Back Button */}
        <div className="text-center mt-5">
          <Link to="/Home" className="btn btn-outline-success px-4 rounded-pill">
            ← Back to Home
          </Link>
        </div>
      </div>

      {/* CTA Section */}
      <section className="text-center bg-success text-white py-5 mt-5">
        <h3 className="fw-bold">Powering a Greener Tomorrow</h3>
        <p className="mt-2 fs-5">
          Renewable energy holds the key to a sustainable planet.
        </p>
        <Link to="/contact" className="btn btn-light rounded-pill px-4 mt-3">
          Contact Us
        </Link>
      </section>
    </>
  );
};

export default Renewable;
